import {
  AI_SUMMARIZER_MAX_FILE_SIZE_MB,
  AI_SUMMARIZER_MAX_MESSAGE_CHARS,
  AI_SUMMARIZER_MAX_PAGES,
} from "astro:env/client";

export const MAX_FILE_SIZE_MB = AI_SUMMARIZER_MAX_FILE_SIZE_MB;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;
export const MAX_MESSAGE_CHARS = AI_SUMMARIZER_MAX_MESSAGE_CHARS;
export const MAX_PAGES = AI_SUMMARIZER_MAX_PAGES;

export const DESKTOP_BREAKPOINT_PX = 1040;
