import { apiHttpClient } from "@/shared/api/api-http-client";
import { API_ROUTES } from "@/shared/api/api-routes";

// ============================================
// Types
// ============================================

export interface SignUpRequest {
  email: string;
  password: string;
  last_uploaded_filename?: string;
}

export interface SignUpResponse {
  userId: string;
  email: string;
  status: string;
}

export interface RevealRequest {
  email: string;
  last_uploaded_filename?: string;
  last_uploaded_file_size?: number;
  funnel?: string;
}

export interface RevealResponse {
  status: string;
  email: string;
}

interface AnonymousSessionResponse {
  userId: string;
  status: string;
}

// ============================================
// Helpers
// ============================================

/**
 * Ensure anonymous session exists before sign-up.
 * Creates one if no auth cookies are present.
 */
const ensureAnonymousSession = async (): Promise<void> => {
  try {
    // Try to get current user - if successful, session exists
    await apiHttpClient.get(API_ROUTES.USER_ME);
  } catch {
    // No session - create anonymous user
    await apiHttpClient.post<AnonymousSessionResponse>(
      API_ROUTES.AUTH_ANONYMOUS_SESSION,
      {}
    );
  }
};

// ============================================
// API Functions
// ============================================

/**
 * Sign up with email and password.
 * User chooses their own password.
 *
 * Flow:
 * 1. Ensure anonymous session exists (creates if needed)
 * 2. Upgrade anonymous user to registered with email/password
 */
export const signUp = async (data: SignUpRequest): Promise<SignUpResponse> => {
  await ensureAnonymousSession();

  const response = await apiHttpClient.post<SignUpResponse>(
    API_ROUTES.AUTH_SIGN_UP,
    {
      email: data.email,
      password: data.password,
      ...(data.last_uploaded_filename && {
        last_uploaded_filename: data.last_uploaded_filename,
      }),
    }
  );

  return response.data;
};

/**
 * Reveal user with email only (password auto-generated).
 * Password is generated by backend and sent to user via email.
 * Use this for quick funnel sign-ups.
 *
 * Flow:
 * 1. Ensure anonymous session exists (creates if needed)
 * 2. Upgrade anonymous user to registered with auto-generated password
 * 3. Backend sends email with the generated password
 */
export const revealUser = async (
  data: RevealRequest
): Promise<RevealResponse> => {
  await ensureAnonymousSession();

  const response = await apiHttpClient.patch<RevealResponse>(
    API_ROUTES.USER_REVEAL,
    {
      email: data.email,
      ...(data.last_uploaded_filename && {
        last_uploaded_filename: data.last_uploaded_filename,
      }),
      ...(data.last_uploaded_file_size && {
        last_uploaded_file_size: data.last_uploaded_file_size,
      }),
      ...(data.funnel && {
        funnel: data.funnel,
      }),
    }
  );

  return response.data;
};
