export enum EProcessingStatus {
  READY = "READY",
  WAITING = "WAITING",
  FAILED = "FAILED",
  WAITING_FOR_CONVERTING = "WAITING_FOR_CONVERTING",
  WAITING_FOR_OCR = "WAITING_FOR_OCR",
  WAITING_FOR_TRANSLATE = "WAITING_FOR_TRANSLATE",
  WAITING_FOR_REMOVE_WATERMARK = "WAITING_FOR_REMOVE_WATERMARK",
  WAITING_FOR_UNLOCK = "WAITING_FOR_UNLOCK",
}
