export const STRAPI_ROUTES = {
  MAIN_PAGE: "/main-page",
  ABOUT_US: "/about-us",
  CONTACT_US_PAGE: "/contact-us",
  LEGAL_PAGES: "/legal-pages",
  LOG_IN: "/log-in",
  SIGN_UP: "/sign-up",
  DATA_LOCALES: "/data-locales",
  SERVICE_PAGES: "/service-pages",
  NAVBAR: "/navbar",
  FOOTER: "/footer",
  GLOBAL_BLOCKS: "/global-blocks",
  GLOBAL_ELEMENTS: "/global-elements",
  BLOG_ARTICLE_PAGES: "/blog-article-pages",
  BLOG_AUTHORS: "/blog-authors",
  BLOG_CATEGORIES: "/blog-categories",
  TEMPLATES_HOME: "/templates-home",
  TEMPLATE_CATEGORIES: "/template-categories",
  TEMPLATE_SUBCATEGORIES: "/template-subcategories",
  TEMPLATE_PAGES: "/template-pages",
};
